project_id = "ijrisuqixfqzmlomlgjb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
additional_redirect_urls = ["https://127.0.0.1:3000"]
apple_enabled = false
azure_enabled = false
bitbucket_enabled = false
discord_enabled = false
facebook_enabled = false
figma_enabled = false
github_enabled = false
gitlab_enabled = false
google_enabled = false
keycloak_enabled = false
linkedin_enabled = false
notion_enabled = false
slack_enabled = false
spotify_enabled = false
twitch_enabled = false
twitter_enabled = false
workos_enabled = false
zoom_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = false

[edge_runtime]
enabled = true
ip_version = "ipv6"
port = 54327
inspector_port = 8083

[analytics]
enabled = false
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcp.json"

[functions.select-component-variations]
verify_jwt = false

[functions.generate-component-content]
verify_jwt = false