-- Update Hero Variation 5 with new grouped parts structure
UPDATE component_variations 
SET 
  available_parts = ARRAY['badge','headline','subheadline','stat1Number','stat1Label','stat2Number','stat2Label','stat3Number','stat3Label','price','priceLabel','moneyBackGuarantee','ctaButton','secondaryButton','ratingStars','rating','certificationIcon','certification','courseTitle','module1Number','module1Title','module2Number','module2Title','module3Number','module3Title'],
  grouped_parts = '[
    {"key": "badge", "value": ["badge"]}, 
    {"key": "headline", "value": ["headline"]}, 
    {"key": "subheadline", "value": ["subheadline"]}, 
    {"key": "courseStats", "value": ["stat1Number", "stat1Label", "stat2Number", "stat2Label", "stat3Number", "stat3Label"]}, 
    {"key": "pricing", "value": ["price", "priceLabel", "moneyBackGuarantee"]}, 
    {"key": "ctaButton", "value": ["ctaButton"]},
    {"key": "secondaryButton", "value": ["secondaryButton"]}, 
    {"key": "trustIndicators", "value": ["ratingStars", "rating", "certificationIcon", "certification"]}, 
    {"key": "coursePreview", "value": ["courseTitle", "module1Number", "module1Title", "module2Number", "module2Title", "module3Number", "module3Title"]}
  ]'::jsonb,
  grouped_parts_labels = '{
    "badge": "Badge",
    "headline": "Headline", 
    "subheadline": "Subheadline",
    "courseStats": "Course Statistics",
    "pricing": "Pricing",
    "ctaButton": "CTA Button",
    "secondaryButton": "Secondary Button",
    "trustIndicators": "Trust Indicators",
    "coursePreview": "Course Preview"
  }'::jsonb,
  default_content = '{
    "badge": "📚 Premium Course",
    "headline": "Master Digital Marketing",
    "subheadline": "Learn from industry experts and transform your career with our comprehensive digital marketing course.",
    "stat1Number": "120+",
    "stat1Label": "Video Lessons",
    "stat2Number": "25h",
    "stat2Label": "Content",
    "stat3Number": "12K+",
    "stat3Label": "Students",
    "price": "$149",
    "priceLabel": "lifetime access",
    "moneyBackGuarantee": "30-day money-back guarantee",
    "ctaButton": "Start Learning Now",
    "secondaryButton": "View Curriculum",
    "ratingStars": "⭐⭐⭐⭐⭐",
    "rating": "4.8/5 (1,243 reviews)",
    "certificationIcon": "🏆",
    "certification": "Certified Program",
    "courseTitle": "Digital Marketing Masterclass",
    "module1Number": "1",
    "module1Title": "HTML & CSS Fundamentals",
    "module2Number": "2",
    "module2Title": "JavaScript & ES6+",
    "module3Number": "3",
    "module3Title": "React & Modern Frontend"
  }'::jsonb,
  character_limits = '{
    "badge": {"max_characters": 50},
    "headline": {"max_characters": 100},
    "subheadline": {"max_characters": 300},
    "stat1Number": {"max_characters": 20},
    "stat1Label": {"max_characters": 30},
    "stat2Number": {"max_characters": 20},
    "stat2Label": {"max_characters": 30},
    "stat3Number": {"max_characters": 20},
    "stat3Label": {"max_characters": 30},
    "price": {"max_characters": 20},
    "priceLabel": {"max_characters": 50},
    "moneyBackGuarantee": {"max_characters": 100},
    "ctaButton": {"max_characters": 30},
    "secondaryButton": {"max_characters": 30},
    "ratingStars": {"max_characters": 20},
    "rating": {"max_characters": 50},
    "certificationIcon": {"max_characters": 10},
    "certification": {"max_characters": 50},
    "courseTitle": {"max_characters": 100},
    "module1Number": {"max_characters": 5},
    "module1Title": {"max_characters": 50},
    "module2Number": {"max_characters": 5},
    "module2Title": {"max_characters": 50},
    "module3Number": {"max_characters": 5},
    "module3Title": {"max_characters": 50}
  }'::jsonb,
  updated_at = NOW()
WHERE component_type = 'hero' AND variation_number = 5;
